config/routes.rb
Rails.application.routes.draw do
  get 'karaoke/index'
  get 'karaoke/add'
  get 'karaoke/play'
  get 'karaoke/next'
  get 'karaoke/prev'
  get 'karaoke/stop'
  get 'karaoke/audio'
  get 'karaoke/clear'
  get 'karaoke/load'
  get 'karaoke/onplay'
  get 'karaoke/onstop'
  get 'songs/import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :songs do
    collection do
      get :search
      get :browse
    end
    get :add_to_playlist
    get :remove_from_playlist
  end
  
  resources :singers do
    resources :songs, shallow: true
    collection do
      get :search
      get :browse
    end
  end
  
  resources :youtubes do
    collection do
      get :search
      get :browse
    end
  end
  
  resources :playlists do 
    resources :songs, shallow: true
  end
  
  root 'karaoke#index'
  
  mount ActionCable.server, at: '/cable'
end

app/models/singer.rb
class Singer < ApplicationRecord
  has_and_belongs_to_many :songs
  
  validates :name, presence: true
  validates_uniqueness_of :name
  
  searchable auto_index: false do
    text :name, :stored => true
  end

  def self.find_by_first_letter_of_name(letter)
    Singer.where("upper(name) LIKE ?", "#{(letter.upcase)}%").order('name')
  end
  
  def self.all_update_songs_count
    Singer.find_each do |singer|
      singer.songs_count = singer.songs.count
      singer.save
    end
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  def index
    browse
  end
  
  def show
  end
  
  def browse
    @letter = params[:letter]
    if @letter.nil?
      @letter = 'A'
    end
    @singers = Singer.find_by_first_letter_of_name(@letter)
    respond_to do |f|
      f.html { render :action => "index" }
      f.js
    end
  end
  
  def search
    @singers = Singer.search do
      keywords params[:query]
    end.results

    respond_to do |f|
      f.html { render :action => "index" }
      f.js
    end
  end
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/singers/_atoz_form.html.erb
<div class="btn-group">
  <button id="atozMenuButton" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    A
  </button>
  <div id="atozMenuDropdown" class="dropdown-menu">
    <% ('A'..'Z').to_a.each do |letter| %>
      <a data-remote="true" class="dropdown-item" href="<%= browse_singers_path(:letter=>letter) %>"><%= letter %></a>
    <% end%>
  </div>
</div>
<div class="clearfix"></div>

app/views/singers/_search_form.html.erb
  <%= form_tag search_singers_path, :method => :get, :class => "my-2 my-lg-0" , :remote => true do %>
    <div class="form-group">
    <%= search_field_tag :query, params[:query], :class => "form-control mr-sm-2", :id => "searchQueryField", :placeholder => "Search singer name" %>
    </div>
  <% end %>

app/views/singers/_singers_list.html.erb
<div class="list-group" id="singersList">
<% if !@singers.nil? %>

  <% @singers.each do |singer| %>
    <a href="<%= singer_songs_path(singer) %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1 singer-name"><%= singer.name %></h5>
        <small><%= pluralize(singer.songs_count, 'song') %></small>
      </div>
    </a>
  <% end %>

<% end %>
</div>

app/views/singers/browse.js.erb
$('#singersList').replaceWith('<%= j render 'singers_list' %>');

$('#atozMenuButton').html('<%= @letter%>');

$("body").trigger("click");

app/views/singers/index.html.erb
<%= render 'karaoke/player_status' %>

<br>

<h1 class="section-title">Singers</h1>

<%= render 'search_form' %>

<p>Browse names starting with</p>
<%= render 'atoz_form' %>

<br>

<%= render 'singers_list' %>

app/views/singers/search.js.erb
$('#singersList').replaceWith('<%= j render 'singers_list' %>');
$('#searchQueryField').blur();
if ($("#navbarCollapse").is(":visible")) {
    $('.navbar-toggler').click();
}