config/routes.rb
Rails.application.routes.draw do
  get 'karaoke/index'
  get 'karaoke/add'
  get 'karaoke/play'
  get 'karaoke/next'
  get 'karaoke/prev'
  get 'karaoke/stop'
  get 'karaoke/audio'
  get 'karaoke/clear'
  get 'karaoke/load'
  get 'karaoke/onplay'
  get 'karaoke/onstop'
  get 'songs/import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :songs do
    collection do
      get :search
      get :browse
    end
    get :add_to_playlist
    get :remove_from_playlist
  end
  
  resources :singers do
    resources :songs, shallow: true
    collection do
      get :search
      get :browse
    end
  end
  
  resources :youtubes do
    collection do
      get :search
      get :browse
    end
  end
  
  resources :playlists do 
    resources :songs, shallow: true
  end
  
  root 'karaoke#index'
  
  mount ActionCable.server, at: '/cable'
end

app/models/song.rb
class Song < ApplicationRecord
  has_and_belongs_to_many :singers
  has_and_belongs_to_many :playlists
  
  validates :title, presence: true
  validates :number, presence: true
  validates :file, presence: true
  
  validates_uniqueness_of :number
  validates_uniqueness_of :file
  
  searchable auto_index: false do
    text :title, :stored => true
    text :number, :stored => true
  end
  
  def self.find_by_first_letter_of_title(letter)
      Song.where("upper(title) LIKE ?", "#{(letter.upcase)}%").order('title')
  end
  
  def update_singer_names
    names = []
    singers.each do |singer|
      names.push(singer.name)
    end
    self.singer_names = names.join(", ")
  end
  
  def associate_singers
    associate_singer(self.singer1)
    associate_singer(self.singer2)
    associate_singer(self.singer3)
    associate_singer(self.singer4)
  end
  
  def associate_singer(singer_name)
    if !singer_name.blank?
      singer = Singer.find_by_name(singer_name)
      if singer.nil?
        logger.info "Singer #{singer_name} does not exist, creating new"
        singer = Singer.new
        singer.name = singer_name
        singer.save
        self.singers << singer
      else
        logger.info "Singer #{singer_name} exist"
        if !self.singers.find_by_id(singer.id)
          logger.info "Adding #{singer.id} to this song"
          self.singers << singer
        end
      end
    end
  end
  
  def add_to_playlist(playlist)
    if !playlist.nil?
      if !self.playlists.find_by_id(playlist.id)
        logger.debug "Adding #{self.title} to #{playlist.name}"
        self.playlists << playlist
      end
    end
  end
  
  def self.all_associate_singers
    Song.find_each do |s|
      s.associate_singers
    end
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @personal_playlists = Playlist.all.order('name')
    if !params[:singer_id].nil?
      @chosen_singer = Singer.find(params[:singer_id])
      if !@chosen_singer.nil?
        @songs = @chosen_singer.songs.order('title')
      end
    elsif !params[:playlist_id].nil?
      @chosen_playlist = Playlist.find(params[:playlist_id])
      if !@chosen_playlist.nil?
        @songs = @chosen_playlist.songs.order('title')
      end
    elsif params[:letter].nil?
      @listing_recently_added_songs = true
      @songs = Song.all.order("created_at DESC").limit(100)
    else
      @letter = params[:letter]
      @songs = Song.find_by_first_letter_of_title(@letter)
    end
    
    respond_to do |f|
      f.html { render :action => "index" }
      f.js
    end
  end
  
  def browse
    index
  end
    
  def new
    @song = Song.new
    @song.number = Song.maximum("number") + 1
    if !params[:youtube_video_id].nil?
      video = Youtube.get_video(params[:youtube_video_id])
      if !video.nil?
        @song.title = video.title
        @song.file = "plugin://plugin.video.youtube/play/?video_id=" + video.id
      end
    end
  end
  
  def show
    @personal_playlists = Playlist.all.order('name')
    @song = Song.find(params[:id])
  end
  
  def create
    @song = Song.new(song_params)
    if @song.save
      @song.associate_singers
      @song.update_singer_names
      Sunspot.commit
      redirect_to @song
    else
      render 'new'
    end
  end

  def edit
    @song = Song.find(params[:id])
  end
  
  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      @song.associate_singers
      @song.update_singer_names
      Sunspot.commit
      redirect_to @song
    else
      render 'edit'
    end
  end
    
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end
  
  def search
    @personal_playlists = Playlist.all.order('name')
    @query = params[:query]
    @songs = Song.search do
      keywords params[:query]
    end.results
    respond_to do |f|
      f.html { render :action => "index" }
      f.js
    end
  end
  
  def add_to_playlist
    @song = Song.find(params[:song_id])
    if !params[:playlist_id].nil?
      @playlist = Playlist.find(params[:playlist_id])
      @song.add_to_playlist(@playlist)
      @song.save
    end
    
    respond_to do |format|
      format.html { redirect_to song_path(@song) }
      format.js
    end
  end
  
  def remove_from_playlist
    @song = Song.find(params[:song_id])
    if !params[:playlist_id].nil?
      @playlist = Playlist.find(params[:playlist_id])
      @song.playlists.delete(@playlist)
      @song.save
    end
    
    respond_to do |format|
      format.html { redirect_to song_path(@song) }
      format.js
    end
  end
  
  private
    def song_params
      params.require(:song).permit(:title, :singer1, :singer2, :singer3, :singer4, :number, :file, :is_youtube_video)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_atoz_form.html.erb
<div class="btn-group">
  <button id="atozMenuButton" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    A
  </button>
  <div id="atozMenuDropdown" class="dropdown-menu">
    <% ('A'..'Z').to_a.each do |letter| %>
      <a data-remote="true" class="dropdown-item" href="<%= browse_songs_path(:letter=>letter) %>"><%= letter %></a>
    <% end%>
  </div>
</div>
<div class="clearfix"></div>

app/views/songs/_atoz_paginator.html.erb
<nav>
  <ul class="pagination ">
    <% ('A'..'G').to_a.each do |letter| %>
      <% if letter == @letter %>
        <li class="page-item active">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>
<nav>
  <ul class="pagination ">
    <% ('H'..'N').to_a.each do |letter| %>
      <% if letter == @letter %>
        <li class="page-item active">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>
<nav>
  <ul class="pagination ">
    <% ('O'..'U').to_a.each do |letter| %>
      <% if letter == @letter %>
        <li class="page-item active">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>
<nav>
  <ul class="pagination ">
    <% ('V'..'Z').to_a.each do |letter| %>
      <% if letter == @letter %>
        <li class="page-item active">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% else %>
        <li class="page-item">
          <%= link_to letter, songs_path(:letter => letter), class: "page-link" %>
        </li>
      <% end %>
    <% end %>
    <% if @letter.nil? %>
      <li class="page-item active">
        <%= link_to 'Number', songs_path, class: "page-link" %>
      </li>
    <% else %>
      <li class="page-item">
        <%= link_to 'Number', songs_path, class: "page-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/songs/_form.html.erb
<%= form_with model: @song, local: true  do |form| %>
  <% if @song.errors.any? %>
    <div class="alert alert-danger" id="error_explanation" role="alert">
      <h4 class="alert-heading">Error!</h4>
      <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, readonly: true, id: :song_number, :class => "form-control"  %>
  </div>
  
  <div class="form-group">
    <%= form.label :title%>
    <%= form.text_field :title , id: :song_title, :class => "form-control"  %>
  </div>
 
  <div class="form-group">
    <%= form.label :singer1, "Singer 1"%>
    <%= form.text_field :singer1 , id: :song_singer1, :class => "form-control"  %>
  </div>
  
  <div class="form-group">
    <%= form.label :singer2, "Singer 2" %>
    <%= form.text_field :singer2 , id: :song_singer2, :class => "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :singer3, "Singer 3"%>
    <%= form.text_field :singer3 , id: :song_singer3, :class => "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :singer4, "Singer 4" %>
    <%= form.text_field :singer4 , id: :song_singer4, :class => "form-control" %>
  </div>
 
  <div class="form-group">
    <%= form.label :file, "File name" %>
    <%= form.text_field :file , id: :song_file, :class => "form-control" %>
  </div>
    
  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/songs/_search_form.html.erb
  <%= form_tag search_songs_path, :method => :get, :class => "my-2 my-lg-0" , :remote => true do %>
    <div class="form-group">
    <%= search_field_tag :query, params[:query], :class => "form-control mr-sm-2", :id => "searchQueryField", :placeholder => "Search title or number" %>
    </div>
  <% end %>

app/views/songs/_songs_list.html.erb
<div class="list-group" id="songsList">
  <% if @letter.nil? and @query.nil? %>
    <h2 class="section-subheading">Recently added songs</h2>
  <% elsif !@letter.nil? %>
    <h2 class="section-subheading">Titles starting with letter "<%= @letter %>"</h2>
  <% elsif !@query.nil? %>
    <h2 class="section-subheading">Titles matching "<%= @query %>"</h2>
  <% end %>
  
<% if !@songs.nil? %>

  <% @songs.each do |song| %>
  <div class="list-group-item list-group-item-action flex-column align-items-start" data-song="<%= song.id %>">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1 song-title"><%= song.title %></h5>
      <a class="btn btn-primary btn-sm" data-remote="true" href="<%= karaoke_add_path + "?id=#{song.number}" %>" role="button"><%= song.number.to_s.rjust(4, '0').rjust(5,' ') %></a>
    </div>
    <p>
      <%= song.singer_names %>
    </p>
    <div class="btn-toolbar" role="toolbar">
      <div class="btn-group mr-2" role="group">
        <a class="btn btn-secondary btn-sm" data-remote="true" href="<%= karaoke_add_path + "?id=#{song.number}" %>" role="button">Sing</a>
      </div>
      <div class="btn-group mr-2" role="group">
        <a class="btn btn-secondary btn-sm" data-remote="false" href="<%= edit_song_path(song) %>" role="button">Edit</a>
      </div>
      <div class="btn-group mr-2" role="group">
        <% if !@personal_playlists.nil? %>
        <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Save</button>
        <div class="dropdown-menu">
          <% @personal_playlists.each do |p| %>
            <a class="dropdown-item <%= 'disabled' if (!@chosen_playlist.nil? and @chosen_playlist.id == p.id) %>" data-remote="true" href="<%= song_add_to_playlist_path(song) + "?playlist_id=#{p.id}"%>"><%= p.name %></a>
          <% end %>
        </div>
        <% end %>
      </div>
      <div class="btn-group mr-2" role="group">
        <% if !@chosen_playlist.nil? %>
          <a class="btn btn-secondary btn-sm" data-remote="true" href="<%= song_remove_from_playlist_path(song) + "?playlist_id=#{@chosen_playlist.id}"%>">Remove</a>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

<% end %>
</div>

app/views/songs/add_to_playlist.js.erb
$('body').click();
<% if !@playlist.nil? %>
alert("Saved <%= raw @song.title %>");
<% end %>

app/views/songs/browse.js.erb
$('#songsList').replaceWith('<%= j render 'songs_list' %>');

$('#atozMenuButton').html('<%= @letter%>');

$("body").trigger("click");

app/views/songs/edit.html.erb
<h1 class="section-title">Edit Song</h1>
  
<%= render 'form' %>

app/views/songs/index.html.erb
<%= render 'karaoke/player_status' %>

<br>

<% if @chosen_singer %>
  <h1 class="section-title"><%= @chosen_singer.name %></h1>
<% elsif @chosen_playlist %>
  <h1 class="section-title"><%= @chosen_playlist.name %></h1>
<% else %>
  <h1 class="section-title">Songs</h1>
  <%= render 'search_form' %>
  <p>Browse titles starting with</p>
  <%= render 'atoz_form' %>
<% end %>

<br>

<%= render 'songs_list' %>

app/views/songs/new.html.erb
<h1 class="section-title">New Song</h1>

<%= render 'form' %>

app/views/songs/remove_from_playlist.js.erb
$('body').click();
<% if !@playlist.nil? %>
alert("Removed <%= raw @song.title %>");
$(".list-group-item[data-song='<%= raw @song.id %>']").remove();
<% end %>

app/views/songs/search.js.erb
$('#songsList').replaceWith('<%= j render 'songs_list' %>');
$('#searchQueryField').blur();
if ($("#navbarCollapse").is(":visible")) {
    $('.navbar-toggler').click();
}

app/views/songs/show.html.erb
<%= render "form" %>