config/routes.rb
Rails.application.routes.draw do
  get 'karaoke/index'
  get 'karaoke/add'
  get 'karaoke/play'
  get 'karaoke/next'
  get 'karaoke/prev'
  get 'karaoke/stop'
  get 'karaoke/audio'
  get 'karaoke/clear'
  get 'karaoke/load'
  get 'karaoke/onplay'
  get 'karaoke/onstop'
  get 'songs/import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :songs do
    collection do
      get :search
      get :browse
    end
    get :add_to_playlist
    get :remove_from_playlist
  end
  
  resources :singers do
    resources :songs, shallow: true
    collection do
      get :search
      get :browse
    end
  end
  
  resources :youtubes do
    collection do
      get :search
      get :browse
    end
  end
  
  resources :playlists do 
    resources :songs, shallow: true
  end
  
  root 'karaoke#index'
  
  mount ActionCable.server, at: '/cable'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_and_belongs_to_many :songs
  validates_uniqueness_of :name
  validates :name, presence: true
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div class="alert alert-danger" id="error_explanation" role="alert">
      <h4 class="alert-heading">Error!</h4>
      <ul>
      <% playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :playlist_name , :class => "form-control" %>
  </div>

  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/playlists/_playlists_list.erb
<div class="list-group" id="playlistsList">
<% if !@playlists.nil? %>

  <% @playlists.each do |playlist| %>
    <a href="<%= playlist_songs_path(playlist) %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1 singer-name"><%= playlist.name %></h5>
        <small><%= pluralize(playlist.songs.count, 'song') %></small>
      </div>
    </a>
  <% end %>

<% end %>
</div>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<%= render 'karaoke/player_status' %>

<br>

<h1 class="section-title">Playlists</h1>

<br>

<%= render 'playlists_list' %>

app/views/playlists/new.html.erb
<h1 class="section-title">New Playlist</h1>

<%= render 'form', playlist: @playlist %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>