config/routes.rb
Rails.application.routes.draw do
  get 'karaoke/index'
  get 'karaoke/add'
  get 'karaoke/play'
  get 'karaoke/next'
  get 'karaoke/prev'
  get 'karaoke/stop'
  get 'karaoke/audio'
  get 'karaoke/clear'
  get 'karaoke/load'
  get 'karaoke/onplay'
  get 'karaoke/onstop'
  get 'songs/import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :songs do
    collection do
      get :search
      get :browse
    end
    get :add_to_playlist
    get :remove_from_playlist
  end
  
  resources :singers do
    resources :songs, shallow: true
    collection do
      get :search
      get :browse
    end
  end
  
  resources :youtubes do
    collection do
      get :search
      get :browse
    end
  end
  
  resources :playlists do 
    resources :songs, shallow: true
  end
  
  root 'karaoke#index'
  
  mount ActionCable.server, at: '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Karaoke 420</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark  bg-dark">
        <%= link_to 'Karaoke 420', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= active_link_to 'Sing', root_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Songs', songs_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Singers', singers_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'YouTube', youtubes_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Playlists', playlists_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Create new song', new_song_path, active: :exclusive, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Create new playlist', new_playlist_path, active: :exclusive, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
      <%= yield %>
      </div>
      <br>
      <footer class="container">
        <p>&copy; Tuan Nguyen <%= Time.current.year %></p>
      </footer>
    </main>    
  </body>
</html>